<?php

require_once './betaClass.php';

/**
 * Test class for My_BetaClass.
 * Generated by PHPUnit on 2014-04-06 at 22:25:31.
 */
class My_BetaClassTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var My_BetaClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new My_BetaClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers My_BetaClass::add
     * @todo Implement testAdd().
     */
    public function testAdd()
    {
    }
}
?>
